POST https://jsbairoube.execute-api.us-west-2.amazonaws.com/prod/builds

###
POST https://jsbairoube.execute-api.us-west-2.amazonaws.com/prod/build
Content-Type: application/json

{
  "buildId" : "abasdf1234",
  "commitHash": "12345",
  "buildConfiguration": "build_config",
  "buildNumber": "3",
  "branchName": "main",
  "buildStarted" : "555555",
  "uploaded" : false
}
###
MPOST https://jsbairoube.execute-api.us-west-2.amazonaws.com/prod/build/abasdf1234

###
