GET https://jsbairoube.execute-api.us-west-2.amazonaws.com/prod/builds
###

POST https://jsbairoube.execute-api.us-west-2.amazonaws.com/prod/build
Content-Type: application/json

{
  "buildId" : "qwerty1",
  "commitHash": "12345",
  "buildConfiguration": "build_config",
  "buildNumber": "3",
  "branchName": "main",
  "buildStarted" : "555555",
  "buildUrl" : "google.com"
}
###

POST https://jsbairoube.execute-api.us-west-2.amazonaws.com/prod/build/qwerty1
Content-Type: application/json

{
  "buildId": "test_artifacts",
  "uploaded": true
}
###

GET https://jsbairoube.execute-api.us-west-2.amazonaws.com/prod/build/qwerty1
###
